[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,--build-id=sha1"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,--build-id=sha1"]
